name: Release
on:
  release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Copy files
        run: |
          mkdir -p ./build/tmp/bin/x64/plugins/cyber_engine_tweaks/mods/ ./build/release/
          rsync -a ./ ./build/tmp/bin/x64/plugins/cyber_engine_tweaks/mods/character_preset_loader/ --exclude={.git/,build/,.gitignore,.github/,README.md}
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: ../release/character_preset_loader_${{ env.RELEASE_VERSION }}.zip
          directory: ./build/tmp/

      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          artifacts: "./build/release/character_preset_loader_${{ env.RELEASE_VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
